apiVersion: v1
kind: Pod
metadata:
  name: test-pod-1
  namespace: drift-control
spec:
  containers:
  - name: centos
    image: centos
    command: ['sh', '-c', 'sleep 999']
    securityContext:
       privileged: true
